# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0kcvv95gy3vsk8rqpzbwhvf3wdizbnm58px6v2vh913v9kzfwd1j";
    aarch64-linux = "100yly01amcisvarjzqp5qdbx0pssy5wxz0lm37qvz149rjpjgnj";
    x86_64-darwin = "0kclibv827g16hmajdc05bmvq3c4fbrn1isrnzj8x91wkxdnylf9";
    aarch64-darwin = "19r7bs31qd692dm6qaj9y445md5zvk1fcxqm351yqrbwap5amk6r";
  };

  urlMap = {
    x86_64-linux = "https://github.com/incredico/nur/releases/download/v0.0.5/hectorsai_0.0.5_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/incredico/nur/releases/download/v0.0.5/hectorsai_0.0.5_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/incredico/nur/releases/download/v0.0.5/hectorsai_0.0.5_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/incredico/nur/releases/download/v0.0.5/hectorsai_0.0.5_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hectorsai";
  version = "0.0.5";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./hectorsai $out/bin/hectorsai
  '';

  meta = {
    description = "Claude-Code-style terminal client for hectors.ai";
    homepage = "https://hectors.ai";
    license = lib.licenses.mit;
    mainProgram = "hectorsai";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
