# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "16vw9mmv15vijkqcr76mkdhnxp8hjzz7x05b5lzns4zx92zw2imy";
    aarch64-linux = "0x1kwkz6hq5k7y2z1pf53gx32iaf2c3kmk568mx1dzlihj9jgzvc";
    x86_64-darwin = "0bmbk9wjdx5b276r1ffvf573vnvfs88fqwqplwrd7ipgbkfbqgp9";
    aarch64-darwin = "10p19zghw2isga1r6jxnsiwjpr7i25h73854w9a3wxji438cg094";
  };

  urlMap = {
    x86_64-linux = "https://github.com/incredico/nur/releases/download/v0.0.4/hectorsai_0.0.4_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/incredico/nur/releases/download/v0.0.4/hectorsai_0.0.4_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/incredico/nur/releases/download/v0.0.4/hectorsai_0.0.4_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/incredico/nur/releases/download/v0.0.4/hectorsai_0.0.4_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hectorsai";
  version = "0.0.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./hectorsai $out/bin/hectorsai
  '';

  meta = {
    description = "Claude-Code-style terminal client for hectors.ai";
    homepage = "https://hectors.ai";
    license = lib.licenses.mit;
    mainProgram = "hectorsai";

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
